### ISSUE TITLE
No matching Method/Function for String.getProperties() found

### ISSUE THREAD

**Issue by cartanga** [cfsimplicity/lucee-spreadsheet#105]
I get the following error when using the info() method on Lucee 5.1.1.65
Called like this: w = application.spreadsheet.info('4010-rows.xls');
The 4010-rows.xls came with the package but I also tried multiple files from different versions of Excel.
The read works just fine on all the files. Thanks.

No matching Method/Function for String.getProperties() found
Stacktrace 	The Error Occurred in
G:\server_all_htdocs\server_prj\system\spreadsheetlibrary\spreadsheet.cfc: line 2208

    2206:
    2207: private struct function xmlInfo( required workbook ){
    2208: var documentProperties=workbook.getProperties().getExtendedProperties().getUnderlyingProperties();
    2209: var coreProperties=workbook.getProperties().getCoreProperties();
    2210: return {

called from G:\server_all_htdocs\server_prj\system\spreadsheetlibrary\spreadsheet.cfc: line 767

**Comment by cfsimplicity** [comment]
Hi. The [info() method ](https://github.com/cfsimplicity/lucee-spreadsheet/wiki/info) takes a _workbook object_, rather than a file path. So basically you need to `read()` the file first then pass the resulting object to `info()`. eg.
```
pathToXls = ExpandPath( "4010-rows.xls" );
workbookObject = application.spreadsheet.read( pathToXls );
info = application.spreadsheet.info( workbookObject );
```
But I like the idea of being able to optionally pass in a file path instead of a workbook object. So I'll raise an enhancement ticket for that.

**Comment by cartanga** [comment]
My misunderstanding, Thanks for the clarification and quick response.
I was trying to get the info on the spreadsheet file and then test if the required workbooks are included in the spreadsheet and then import them in the database.
Regards

**Comment by cfsimplicity** [comment]
No problem. The latest master version (0.11.0) has the enhancement so you can now pass in a file path so you don't have to read the workbook object first. You do need to pass the full file path though, not just the file name.
