### ISSUE TITLE
Allow datatype to be specified when using setCellValue()

### ISSUE THREAD

**Issue by cfsimplicity** [cfsimplicity/lucee-spreadsheet#112]
See: https://github.com/cfsimplicity/lucee-spreadsheet/pull/111

Add the ability to override the auto type detection when setting a cell value (as ACF now allows).

Possible types: String, Numeric, Date or Boolean

**Comment by john5onCheng** [comment]
Hi, apologise for the mistake, I have corrected the logic and create another PR. The project that I working  on currently was having cell showing incorrect value.
e.g. 
> 0162220494 telephone number is set as boolean. 
> 01-23112 member number is set as date

**Comment by cfsimplicity** [comment]
A `type` option for `setCellValue()` is now available with v1.2.0

I've also improved the default type handling so that your two examples should now work as expected without having to specify the type.
