### ISSUE TITLE
spreadsheet.download does not serve XLSX documents

### ISSUE THREAD

**Issue by sebgmc** [cfsimplicity/lucee-spreadsheet#133]
With this function:

spreadsheet.download(workbook=workbookClientReport,filename=filename,contentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");

I expect to get an XLSX file served, but no matter what I do I always get an XLS.

Anyone experiencing this or have a solution how to circumvent this issue?

I would like this to work, as all other calls to the spreadsheet-lib gives me an XLSX, either automagically or when using the parameter xmlformat=true in the function-call.

One extension to rule them all in our webapp, please ;-)

**Comment by cfsimplicity** [comment]
To get an `.xlsx` file from `download()` you need to make sure the workbook object you are passing in is an XML type. Otherwise the extension is set to ".xls" regardless of the content type you specify.

What do you get when you do this?
```
WriteDump( spreadsheet.isXmlFormat( workbookClientReport ) );
```

**Comment by sebgmc** [comment]
@cfsimplicity that did the trick! Adding xmlformat=true to the workbookFromQuery function-call made it automagically a XML-type object and hence the download function serves an XLSX. Great, thnx!

workbookClientReport = spreadsheet.workbookFromQuery(data=data,xmlformat=true);
// do some workbook manipulations and then:
spreadsheet.download(workbookClientReport,filename);
