### ISSUE TITLE
AddRow() Implementation is very slow

### ISSUE THREAD

**Issue by AlexD1979** [cfsimplicity/lucee-spreadsheet#135]
For generating an Excel Sheet with 115 rows and 30 columns the script needs 15 seconds. In a debug log I can see, most of the time, 8 sec. are used to call addRow method.
![cfspreadsheet_executiontime](https://user-images.githubusercontent.com/25854347/31728232-02eab336-b42c-11e7-8106-c12be6913321.PNG)

[LaunchRisksStatusExcelExporter.cfc.txt](https://github.com/cfsimplicity/lucee-spreadsheet/files/1395324/LaunchRisksStatusExcelExporter.cfc.txt)

**Comment by cfsimplicity** [comment]
Hi Alexander, can you please email me the `programs` data array so that I can run your code?

**Comment by AlexD1979** [comment]
Hello Julian,
I think you don´t need the data array, please make a loop over addRow and you will see the bottle neck addRow.

Best regards
Alexander




Von: Julian Halliwell [mailto:notifications@github.com]
Gesendet: Mittwoch, 18. Oktober 2017 18:10
An: cfsimplicity/lucee-spreadsheet <lucee-spreadsheet@noreply.github.com>
Cc: Alexander Diedler <adiedler@tecracer.de>; Author <author@noreply.github.com>
Betreff: Re: [cfsimplicity/lucee-spreadsheet] AddRow() Implementation is very slow (#135)


Hi Alexander, can you please email me the programs data array so that I can run your code?

**Comment by sebgmc** [comment]
Hi @AlexD1979 , are you sure there is nothing else going on here? I have implemented this library lately and have never come across this. I just created a simple spreadsheet with data from a database, calling addRow 23 times (with 31 columns per row). Spreadsheet was done in no time. What I do experience once in a while is that initial load of the library into memory (first call of library after restart ACF or Lucee) is very slow. But all subsequent calls are lightning fast. Just my 2 cents ;-)

**Comment by cfsimplicity** [comment]
Hi Alexander. I'm not seeing any bottleneck with a simple test of `addRow()` looping a thousand times:
```
spreadsheet = New luceeSpreadsheet.Spreadsheet();
workbook = spreadsheet.newXlsx();
rowdata = "one,two,three,four,five";
iterations = 1000;
stopwatch variable="milliseconds"{
	loop from=1 to=iterations index="i"{
		spreadsheet.addRow( workbook, rowdata );
	}
}
dump( milliseconds );
```
In my Lucee 5.2.5 dev environment this as averaging between 100 and 200 milliseconds. 

As Sebastiaan says I think there is probably something in your data or environment which is causing the issue.

**Comment by AlexD1979** [comment]
Hello Julian,
I got the bottleneck, the debugging was enabled and debugging increase the time of processing 10 times. Without debugging enabled in Lucee, it was around 4 seconds and full acceptable.

Best regards
Alexander


Von: Julian Halliwell [mailto:notifications@github.com]
Gesendet: Donnerstag, 19. Oktober 2017 09:34
An: cfsimplicity/lucee-spreadsheet <lucee-spreadsheet@noreply.github.com>
Cc: Alexander Diedler <adiedler@tecracer.de>; Mention <mention@noreply.github.com>
Betreff: Re: [cfsimplicity/lucee-spreadsheet] AddRow() Implementation is very slow (#135)


Hi Alexander. I'm not seeing any bottleneck with a simple test of addRow() looping a thousand times:

spreadsheet = New luceeSpreadsheet.Spreadsheet();

workbook = spreadsheet.newXlsx();

rowdata = "one,two,three,four,five";

iterations = 1000;

stopwatch variable="milliseconds"{

        loop from=1 to=iterations index="i"{

               spreadsheet.addRow( workbook, rowdata );

        }

}

dump( milliseconds );

In my Lucee 5.2.5 dev environment this as averaging between 100 and 200 milliseconds.

As Sebastiaan says I think there is probably something in your data or environment which is causing the issue.
