### ISSUE TITLE
Setting cell type to Numeric doesn't work as anticipated

### ISSUE THREAD

**Issue by Tim-Brenner** [cfsimplicity/lucee-spreadsheet#140]
I'm trying to generate a spreadsheet that contains numeric values like 2.10, that include x number of trailing zeroes in the decimal.  I've set the formatting on the cell to be 0.00, and set the type to numeric, but the resultant spreadsheet has the data type for the cell set to general instead of number, so the additional 0's are not appearing.  Is this functioning as anticipated, and if so, can a new type be added that will force the spreadsheet to display the values as type 'number'?  Thanks for the info/help.

**Comment by cfsimplicity** [comment]
Hi Tim.  The following appears to work as expected on the latest version:
```
s = new luceeSpreadsheet.Spreadsheet(); // adjust for your path to the library cfc
wb = s.new();
s.formatCell( wb, { dataformat: "0.00" }, 1, 1 );
s.setCellValue( wb, "2.10", 1, 1, "numeric" );
s.download( wb, "test" );
```
This is giving me a sheet with an A:1 value of `2.10`. Works even without specifying the `type` as numeric in `setCellValue()`.

Does the above work for you, and is it different from your code that isn't producing the right results?

**Comment by Tim-Brenner** [comment]
Thanks not only for the quick response, but for the example.  I'd missed needing to use formatCell.  It worked perfectly.  Thanks for your help!
