### ISSUE TITLE
Support for ACF < 11

### ISSUE THREAD

**Issue by joshknutson** [cfsimplicity/lucee-spreadsheet#141]
Working on a project that requires that I still have to support ACF 9, would it be possible to support down to that version? Or would that be too much effort, supporting CF10 doesn't looks like it wouldn't be too bad to support, but the CF9 looks like it would be a fair amount of work.

**Comment by cfsimplicity** [comment]
Hi Josh.

Sorry, but if anything I'll be wanting to move the ACF compatibility forwards as old versions are End of Lifed. 

Effort to support old versions is wasted given that the number of people using them will only dwindle.

It also hamstrings development preventing newer language features being used for performance and code readability/efficiency.

And I'm sure you don't need me to tell you that, as CF9's EoL was nearly 4 years ago, any server running that version is a serious security risk.

Julian

**Comment by joshknutson** [comment]
Fair enough
