### ISSUE TITLE
addRows() doesn't apply column offset to header row when using includeQueryColumnNames

### ISSUE THREAD

**Issue by crslsc** [cfsimplicity/lucee-spreadsheet#157]
In addRows(), if I use the optional column offset argument the data is offset to that column number, but if I also set includeQueryColumnNames to true, the header row with the column names is generated in column 1, ignoring the column offset.

**Comment by cfsimplicity** [comment]
Hi, thanks for reporting this. You're quite right, an offset column value wasn't being respected.

I've pushed a fix with tests to the develop branch. Would you mind just confirming it works for you now? I'll then update master.

Thanks.

**Comment by crslsc** [comment]
Confirmed that it's fixed in the dev branch. Thank you very much for the project and for the fast response!
