### ISSUE TITLE
Support decryption of encrypted binary (XLS) spreadsheets

### ISSUE THREAD

**Issue by jeaguilar** [cfsimplicity/lucee-spreadsheet#162]
Since Spreadsheet.read() only supports opening encrypted XML format (.xlsx) spreadsheets, I use the following workaround to decrypt a binary format file (.xls):

https://gist.github.com/jeaguilar/157aa208ee90a36e53fc3ca0e012f179

**Comment by cfsimplicity** [comment]
Thanks, Juan! I wasn't aware of that factory method signature which appears to be a convenience wrapper for the decryption code that's in the [POI docs](http://poi.apache.org/encryption.html).

When I tackled encryption/decryption some time ago I could only get it to work on XLSX files. Perhaps things have improved in POI 4.0 without it being documented.

Looks like this will simplify things greatly. Look out for an update soon!

**Comment by cfsimplicity** [comment]
Juan, I've incorporated your workaround into the [develop](https://github.com/cfsimplicity/lucee-spreadsheet/tree/develop) branch. Could you please verify that it's working for you?

Thanks
Julian.

**Comment by jeaguilar** [comment]
That's excellent! It works like a champ.

```
SPREADSHEET = new spreadsheetDevelop.Spreadsheet();
qryFromFile = SPREADSHEET.read( src="/tmp/EncryptedSpreadsheet.xls", format="query", password="S3cr37P@ssw0rd" );
writeDump( qryFromFile );
```

Thanks Julian!

**Comment by cfsimplicity** [comment]
Thanks again for suggesting it, Juan. Looks like that signature was added to POI 4 years ago but the docs have never been updated. Would've saved me a lot of bother if I'd known about it, but better late than never!

Will push a new version with this to master shortly (which will also include the latest POI 4.1.0 release).
