### ISSUE TITLE
Set Margin

### ISSUE THREAD

**Issue by georgecfwebtools** [cfsimplicity/lucee-spreadsheet#167]
Is there a way to set worksheet margin?

I would create a Excel file and setup everything so user could open and print. Now I could almost do anything I would but margin.

I checked all functions and could not find a method to set margin.

Is there a way to do it?

**Comment by cfsimplicity** [comment]
Hi, can you just confirm that what you want to do is set the _page_ margins of a specified sheet when printed?

If so then yes, that should be possible. I will need to create some new methods to handle that.

**Comment by georgecfwebtools** [comment]
Thanks!
When creating a worksheet, currently the margin will be default and no way to change it.  It would be good to adjust the margin.

Currently I extend the cfc to call setMargin method of POI, but it would be to have the function inside the library.

**Comment by cfsimplicity** [comment]
OK, I'll try and add support for that in the develop branch as soon as I get time. My instinct is to have separate methods for each type of margin, e.g. `setSheetTopMargin()`, `setSheetFooterMargin()` etc.

**Comment by cfsimplicity** [comment]
I've added 6 new methods:
```
setSheetTopMargin( workbook, marginSize[, sheetName[, sheetNumber] ] )
setSheetBottomMargin( workbook, marginSize[, sheetName[, sheetNumber] ] )
setSheetLeftMargin( workbook, marginSize[, sheetName[, sheetNumber] ] )
setSheetRightMargin( workbook, marginSize[, sheetName[, sheetNumber] ] )
setSheetHeaderMargin( workbook, marginSize[, sheetName[, sheetNumber] ] )
setSheetFooterMargin( workbook, marginSize[, sheetName[, sheetNumber] ] )
```
Could you please download the **develop** branch and test? Thanks.

**Comment by georgecfwebtools** [comment]
It worked perfectly! Thank you very much!
