### ISSUE TITLE
Fit in one page width

### ISSUE THREAD

**Issue by georgecfwebtools** [cfsimplicity/lucee-spreadsheet#168]
As building a report, my last request is to make the Excel sheet print ready.

I checked the functions, did not find "Fit all columns on one page” setting. It would be great to have it so it will be very user friendly.

Thanks!

**Comment by cfsimplicity** [comment]
OK, unfortunately this is too late for the new version I've just pushed to master with the new margin methods. I'll look at this one when I get chance and add it to the next release.

**Comment by georgecfwebtools** [comment]
That is fine, not need it right now, just good to have it.

**Comment by cfsimplicity** [comment]
Hi. I've added a method `setFitToPage( workbook, state[, pagesWide[, pagesHigh ] ] )`.

When you set the `state` to `true` it should preset the print options to squeeze all the sheet's contents into one page by default.

You can specify how many pages wide and high you want to fit the content into. To only fit the columns, set `pagesHigh` to 0.

I don't have Excel but have tested it on OpenOffice.

Please can you test this on develop and let me know if it does what you want? Thanks.

**Comment by georgecfwebtools** [comment]
Tested. it worked in my test. 

Thank you for your support!
