### ISSUE TITLE
Using autoSizeColumns with a Streaming XLSX workbook causes an exception

### ISSUE THREAD

**Issue by cfsimplicity** [cfsimplicity/lucee-spreadsheet#171]
Using `autoSizeColumn()`, or the `autoSizeColumns=true` argument with `addRow()` or `addRows()`, if the workbook format is Streaming XLSX (SXSSF) an exception is thrown: "Could not auto-size column. Make sure the column was tracked prior to auto-sizing the column."

**Comment by cfsimplicity** [comment]
Using `autoSizeColumns=true` with `addRow()` or `addRows()` and a Streaming XLSX (SXSSF) workbook throws an exception: "Could not auto-size column. Make sure the column was tracked prior to auto-sizing the column."

**Comment by JamoCA** [comment]
I initially tried that, but haven't returned to test it.  I'm currently adding a column header, adding a bold style and freezing it.  I then use the autoSizeColumn() function based on logic for each column's datatype.  _(Any data types that allow over 50 characters is set manually using spreadsheet.setColumnWidth().)_

I posted my sample source code here:
https://gist.github.com/JamoCA/181f7c420930bd7fe1a0db5b07959e83

**Comment by cfsimplicity** [comment]
Thanks. You can fix the date formatting problem by changing DATETIME to TIMESTAMP - see https://github.com/cfsimplicity/lucee-spreadsheet/issues/173

There are a few other ways you could refactor your code. See my version here:
https://gist.github.com/cfsimplicity/2edbe40b8e52f16079818fa9a9ced589
