### ISSUE TITLE
Color index lookup is using a deprecated enum class

### ISSUE THREAD

**Issue by cfsimplicity** [cfsimplicity/lucee-spreadsheet#178]
The private `getColorIndex()` method inherited from the old Railo extension is using an apparently deprecated enum: [org.apache.poi.ss.usermodel.IndexedColors](https://poi.apache.org/apidocs/dev/org/apache/poi/ss/usermodel/IndexedColors.html). This needs replacing with [org.apache.poi.hssf.util.HSSFColor.HSSFColorPredefined](https://poi.apache.org/apidocs/dev/org/apache/poi/hssf/util/HSSFColor.HSSFColorPredefined.html).

The lists are the same except for 9 additional variants in org.apache.poi.ss.usermodel.IndexedColors suffixed with the number 1:

BLACK1, WHITE1, RED1, BRIGHT_GREEN1, BLUE1, YELLOW1, PINK1, TURQUOISE1, LIGHT_TURQUOISE1

The documentation has always pointed to the correct HSSFColorPredefined class so I don't consider this to be a breaking change. Any colours ending in 1 can be mapped to the corresponding value to avoid potential "invalid" errors.

**Comment by JamoCA** [comment]
Thanks for this... I couldn't get this to work when I isolated the code and tested it.  (I thought it was just me.)  This probably contributed to my inability to pass generic color names.
