### ISSUE TITLE
Values Cast as "int" are Exported with "Number Stored as Text"

### ISSUE THREAD

**Issue by JamoCA** [cfsimplicity/lucee-spreadsheet#181]
When transforming or adding data in CF Queries, I often use `javacast("int")`, so that I can perform additional query-of-query function with the data.  I've noticed that queries straight from the Microsoft SQL JDBC extension are being saved as text.  Excel displayed a green left-corner flag and indicates "Number Stored as Text".

The private `getQueryColumnFormats()` function needs to be expanded to accept "INT" in addition to "INTEGER". I'm not sure if this is specific to ACF or my JDBC driver, but adding "INT" fixed my "Number stored as text" issue.

**Comment by cfsimplicity** [comment]
OK, James. have added INT to the list of types detected as numeric. Use the develop branch to check it's working for you. Thanks.

**Comment by JamoCA** [comment]
That's the same exact code that I'm use which works.  Thanks!
