### ISSUE TITLE
formatCellRange did not accept HEX values

### ISSUE THREAD

**Issue by brakop** [cfsimplicity/lucee-spreadsheet#203]
Not sure if this is related to #177, but I was intending to use hex codes (e.g #684099) for the color in a format range, here's the code:
Erroring Code:
`spreadsheet.formatCellRange( workbook,{bold="true",color="white",fgcolor="##684099",fontsize=12},1,1,1,arrayLen(listtoArray(data.ColumnList,",")) );
Got me this error:
`![image](https://user-images.githubusercontent.com/17260055/96068181-15265500-0ee7-11eb-8ea9-2f0c296086dc.png)

Workaround was just to use the RGB triplet:
spreadsheet.formatCellRange( workbook,{bold="true",color="white",fgcolor="104,64,153",fontsize=12},1,1,1,arrayLen(listtoArray(data.ColumnList,",")) );

Not a big deal, and other than that been a breeze to use this! Thanks!

**Comment by cfsimplicity** [comment]
Hi. Hex value support was only introduced in version 2.11.0. From the error it looks like you're using an older version.

Can you try with the latest version 2.11.1 (which fixed a bug with hex handling)?

**Comment by brakop** [comment]
Ha, yeah I'm running 2.7.0. That would explain it! Upgrade in progress, but I'm going to close this as ID10T error. Cheers!
