### ISSUE TITLE
Public access to function buildCellStyle

### ISSUE THREAD

**Issue by vivienwong** [cfsimplicity/lucee-spreadsheet#204]
Hi,

Is it possible to have Spreadsheet$buildCellStyle() function access changed to public so that we can call this function to generate commonly used cell styles? 

Thanks

**Comment by cfsimplicity** [comment]
Hi Vivien. Can you give me an example of how you would use this and why the existing public formatting methods (which all use this private method) wouldn't be adequate?

Thanks.

**Comment by vivienwong** [comment]
Hi Julian,

Sample usage if buildCellStyle() is publicly accessible:
```
var headerStyle = Spreadsheet.buildCellStyle( workbook=workbook
	, format={ fontsize          = 9
	, bold              = true
	, alignment         = "CENTER"
	, verticalalignment = "CENTER"
	, fillpattern       = "SOLID_FOREGROUND"
	, fgcolor           = "183,218,224"
	, textwrap          = false
} );

Spreadsheet.formatCell( workbook=workbook, row=1, column=1, format={}, cellStyle=headerStyle );
Spreadsheet.formatCell( workbook=workbook, row=1, column=3, format={}, cellStyle=headerStyle );
Spreadsheet.formatCell( workbook=workbook, row=1, column=5, format={}, cellStyle=headerStyle );

Spreadsheet.getWorkbookCellStylesTotal( workbook ); // returns 1 style
```
Notice headerStyle can easily be used repeatedly throughout the workbook onto different columns / region by setting it into cellStyle argument without registering a new style.

Whereas if we use what is available at the moment, e.g. formatCell with format argument (no cellStyle value), a different style is registered each time we call formatCell():
```
Repeating the following onto 3 different columns,
Spreadsheet.formatCell( workbook=workbook, row=1, column=1, format=format={ fontsize          = 9
	, bold              = true
	, alignment         = "CENTER"
	, verticalalignment = "CENTER"
	, fillpattern       = "SOLID_FOREGROUND"
	, fgcolor           = "183,218,224"
	, textwrap          = false
}  );

Spreadsheet.getWorkbookCellStylesTotal( workbook ); // returns 3 styles
```

Which easily hit the maximum allowed style: 64000 style in a .xlsx Workbook for a big document with repeated formatting.

I'm happy to submit a PR if this is fine.

Thanks

**Comment by cfsimplicity** [comment]
Thanks Vivien, that makes complete sense. Great idea! Let me think it through though as that method was intended for internal use and it may need a slightly different public interface.

**Comment by cfsimplicity** [comment]
Vivien, just refreshing my memory on how formatting is implemented currently...

If you use the multiple cell formatting functions, i.e. `formatRange`, `formatColumn`, `formatColumns`, `formatRow` and `formatRows`, then only one CellStyle is registered, no matter how many cells you are formatting.

I added the optional `cellStyle` argument to each of the formatting functions to allow that re-use happen internally, but didn't document it as it was intended for internal use only.

I guess my assumption was that if people are applying the same format to multiple cells they would use one of those methods, not repeated use of `formatCell()` as in your example, i.e. instead of:
```
Spreadsheet.formatCell( workbook=workbook, row=1, column=1, format={ bold: true } );
Spreadsheet.formatCell( workbook=workbook, row=1, column=3, format={ bold: true } );
Spreadsheet.formatCell( workbook=workbook, row=1, column=5, format={ bold: true } );
```
... you would do:
```
Spreadsheet.formatColumns( workbook=workbook, format={ bold: true }, range="1,3,5" ):
```
But on reflection I can see that in some situations you may well end up looping over one or more of these functions applying the same format, which would be inefficient and could result in hitting the CellStyle maximum (only 4K for binary xls).

**Comment by vivienwong** [comment]
Hi Julian, 

I did consider using formatting cells in bulk, but there is a caveat of: _this should only be used when formatting a limited number of cells (you may run into errors if applied to too many cells)_ as mentioned https://github.com/cfsimplicity/lucee-spreadsheet/wiki/formatColumns for example.

Also, the bulk format, format***() does not work across different sheets. Even if bulk formatting is applied, it still has to be repeated unnecessarily over different sheets.

I've tested changing buildCellStyle() to public and works perfectly fine. Just wondering any chance this could be released soon?

Thanks

**Comment by cfsimplicity** [comment]
That warning about errors only applies if you set the `overwriteCurrentStyle` flag to false.

But good point about multiple sheets. I do agree there's a case for a public method to create cellstyles independently, and I'll do my best to get it done shortly. I have to think it through though - there's likely to be more to it than just changing the method access.

**Comment by cfsimplicity** [comment]
Vivien, I want to keep the `buildCellStyle()` method private but I've added a new `createCellStyle()` method as a public interface to it. You pass it the workbook and format struct in exactly the same way.

Could you please test it in the [develop branch](https://github.com/cfsimplicity/lucee-spreadsheet/tree/develop)?

**Comment by vivienwong** [comment]
Hi Julian,

I've tested `createCellStyle()` function in the develop branch and it works well. Awaiting the release for this.

Thank you very much for your replies and swift action!
