### ISSUE TITLE
Error: ARGUMENTSBOLDHEADERROW

### ISSUE THREAD

**Issue by syzzle** [cfsimplicity/lucee-spreadsheet#206]
On Lucee 5.3.7.44 I am getting the following error when I initiate a new spreadsheet using version 2.12.0

"variable [ARGUMENTSBOLDHEADERROW] doesn't exist"

**Comment by cfsimplicity** [comment]
Apologies, looks like a typo in `downloadFileFromQuery()`. Fix coming right up.

**Comment by syzzle** [comment]
You rock - thank you!

Brian
