### ISSUE TITLE
createCellStyle() is not a function

### ISSUE THREAD

**Issue by GaryStanton** [cfsimplicity/lucee-spreadsheet#207]
First, thanks for the awesome library!

According to the wiki, formatting cells is ideally done with the `createCellStyle()` function.
https://github.com/cfsimplicity/lucee-spreadsheet/wiki/createCellStyle

The example shows this as being a function of the `spreadsheet` class, but from what I can tell that function actually belongs to the `workbook`, and the usage is somewhat more verbose.
There appears to be a _wrapper_ for it named `buildCellStyle()`, which works great - but is currently a private function. I've found if I simply change this to public, I'm able to use this function interchangably with the arguments detailed in the docs for `createCellStyle()`, so I'm not sure if the docs are incorrect, or if that function (`buildCellStyle`) is incorrectly named, or if there should be a public wrapper function named `createCellStyle()`. 

I've also noticed that the formatting functions (`formatRow()`, for example) have `format` set as a required argument, which it needn't be if a `cellStyle` is being passed. Currently I'm just passing an empty struct.

**Comment by GaryStanton** [comment]
UGH! How embarrasing... I've _just_ realised I'm using an older version and the public function was only added 2 weeks ago... Ignore me. Carry on...

**Comment by cfsimplicity** [comment]
No worries, Gary! Thanks for the kind words.
