### ISSUE TITLE
Forgebox version broken

### ISSUE THREAD

**Issue by Daemach** [cfsimplicity/lucee-spreadsheet#210]
I'm suddenly getting this in commandbox when running update.  Updating doesn't fix it - looks like forgebox is confused about the version.

![image](https://user-images.githubusercontent.com/12553953/100523045-1c858300-3162-11eb-8ea0-846dbdf12a0f.png)

**Comment by cfsimplicity** [comment]
I'm using CommandBox 5.1.1 and it seems to be working ok. The box.json seems fine and the version is displaying ok on the Forgebox website: https://www.forgebox.io/view/lucee-spreadsheet#versions

Maybe a problem with the new RC version of CommandBox you're using?

**Comment by Daemach** [comment]
Apparently it was trying to pull directly from github instead of via forgebox and that caused the problem.  I don't know how that happened as I installed it with install lucee-spreadsheet" in commandbox.  In any case, uninstall and reinstall seems to have fixed it.  Sorry about the false start.
