### ISSUE TITLE
Add delimiter as option for downloadCsvFromFile()

### ISSUE THREAD

**Issue by sebgmc** [cfsimplicity/lucee-spreadsheet#212]
Is it possible to change the delimiter of the value-separator in the downloadCsvFromFile() function?

It is now a comma ( , ), but I'd like to change it to a semicolon ( ; ) or a pipe is needed ( | ).

Something like: `spreadsheet.downloadCsvFromFile(src=spreadsheetFilePathAndName, filename=spreadsheetFileName, delimiter=";");`

Can this be done? That would help immensely when there are comma's in the text / values for each column. Instead of having to add quotes around each value in each cell to escape commas.

Thnx up front.

**Comment by sebgmc** [comment]
Let me try and get a testcase isolated from our webapp and get back to you asap.

**Comment by sebgmc** [comment]
Provided testcases, worked perfectly on DEV-branch, go 4 LIVE in my opinion!

**Comment by cfsimplicity** [comment]
OK that's all done. Have a good weekend!

**Comment by sebgmc** [comment]
Thnx a bunch!

Going to production in 3-2-1...

Sebastiaan
--
*Onlinebase BV*
Rabobank: NL56RABO0147656230
KvK Den Haag: 28114827
BTW: NL821502360B01
Twitter:  @onlinebaseNL <http://twitter.com/onlinebaseNL>
Internet: https://onlinebase.nl/
       http://fusioneers.nl/

De informatie opgenomen in dit bericht kan vertrouwelijk zijn en is
uitsluitend bestemd voor de geadresseerde. Indien u dit bericht onterecht
ontvangt, wordt u verzocht de inhoud niet te gebruiken en de afzender
direct te informeren door het bericht te retourneren.

Denk aan het milieu voordat u deze e-mail print.
