### ISSUE TITLE
2.18.0 error: setActiveSheetNameOrNumber() function

### ISSUE THREAD

**Issue by JamoCA** [cfsimplicity/lucee-spreadsheet#235]
The new `setActiveSheetNameOrNumber()` function in v2.18.0 (line 2161) is throwing an error on CF2016u17.

![LuceeSpreadsheet_Error_20210415121141](https://user-images.githubusercontent.com/1112671/114925316-cbf68580-9de3-11eb-9ce2-d9d89f8b6008.png)

I replaced the CFC, lib-osgi.jar file, restarted and couldn't get past this error.  I reverted back to 2.17.

**Comment by cfsimplicity** [comment]
Dang, missing semi-colon! Strange, I ran the test suite against all the ACF engines and they didn't complain then.

Will have a hot fix out pronto.

**Comment by cfsimplicity** [comment]
Fixed in v2.18.1
