### ISSUE TITLE
"zip END header not found" on read()

### ISSUE THREAD

**Issue by cormip** [cfsimplicity/lucee-spreadsheet#239]
Downloaded and installed components:

lib-osgi.jar
osgiLoader.cfc
Spreadsheet.cfc

Lucee v5.3.7.48

Very simple MS Excel file used as a test (attached)

[movies.xls](https://github.com/cfsimplicity/lucee-spreadsheet/files/6407058/movies.xls)

Raw_Trace: `helper.osgiloader_cfc$cf.udfCall(/oatComponents/helper/osgiLoader.cfc:25)`

Stack Trace

`lucee.runtime.exp.NativeException: zip END header not found at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1587) at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1441) at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1450) at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1263) at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225) at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:706) at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:240) at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:171) at java.base/java.util.jar.JarFile.<init>(JarFile.java:349) at java.base/java.util.jar.JarFile.<init>(JarFile.java:320) at java.base/java.util.jar.JarFile.<init>(JarFile.java:286) at lucee.runtime.osgi.BundleInfo.<init>(BundleInfo.java:92) at lucee.runtime.osgi.BundleFile.<init>(BundleFile.java:62) at lucee.runtime.osgi.BundleFile.getInstance(BundleFile.java:55) at lucee.runtime.osgi.BundleFile.getInstance(BundleFile.java:48) at lucee.runtime.osgi.OSGiUtil.installBundle(OSGiUtil.java:131) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:567) at lucee.runtime.reflection.pairs.MethodInstance.invoke(MethodInstance.java:56) at lucee.runtime.java.JavaObject.call(JavaObject.java:265) at lucee.runtime.java.JavaObject.call(JavaObject.java:287) at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785) at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710) at helper.osgiloader_cfc$cf.udfCall(/oatComponents/helper/osgiLoader.cfc:25) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344) at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217) at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779) at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785) at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710) at helper.osgiloader_cfc$cf.udfCall(/oatComponents/helper/osgiLoader.cfc:18) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344) at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:681) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568) at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1917) at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:864) at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1729) at helper.spreadsheet_cfc$cf.udfCallc(/oatComponents/helper/Spreadsheet.cfc:1769) at helper.spreadsheet_cfc$cf.udfCall(/oatComponents/helper/Spreadsheet.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344) at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217) at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779) at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785) at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710) at helper.spreadsheet_cfc$cf.udfCallc(/oatComponents/helper/Spreadsheet.cfc:1745) at helper.spreadsheet_cfc$cf.udfCall(/oatComponents/helper/Spreadsheet.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344) at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217) at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779) at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785) at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710) at helper.spreadsheet_cfc$cf.udfCalle(/oatComponents/helper/Spreadsheet.cfc:2048) at helper.spreadsheet_cfc$cf.udfCall(/oatComponents/helper/Spreadsheet.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344) at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217) at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779) at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785) at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710) at helper.spreadsheet_cfc$cf.udfCall8(/oatComponents/helper/Spreadsheet.cfc:1238) at helper.spreadsheet_cfc$cf.udfCall(/oatComponents/helper/Spreadsheet.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344) at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:681) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568) at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1917) at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:864) at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1729) at admin.air_data_import_cfm585$cf$9.call(/admin/air-data-import.cfm:67) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:945) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:837) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:216) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:42) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2416) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2406) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2381) at lucee.runtime.engine.Request.exe(Request.java:43) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1170) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1116) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.base/java.lang.Thread.run(Thread.java:831) Caused by: java.util.zip.ZipException: zip END header not found ... 110 more`

**Comment by cfsimplicity** [comment]
Hi, I can't replicate that using Lucee 5.3.7.48. I set up a test install of v2.18.2 as follows:
![Untitled](https://user-images.githubusercontent.com/456718/116744021-aa0b1e80-a9f1-11eb-8b99-77532b5809b4.png)
`index.cfm` contains:
```
<cfscript>
spreadsheet = New Spreadsheet();
data = spreadsheet.read( ExpandPath( "movies.xls" ), "query" );
dump( data );
</cfscript>
```
and the result is:
![Untitled2](https://user-images.githubusercontent.com/456718/116744125-cc04a100-a9f1-11eb-846d-dfdda802b68c.png)

What version of Java are you using?
```
dump( server.java.version );
```
It may be the `lib-osgi.jar` is corrupted for some reason. Try downloading a new copy and then running the following method on your spreadsheet library instance:
```
spreadsheet.flushOsgiBundle();
```

**Comment by cormip** [comment]
OK, cool! The issue must have been either a corrupt `lib-osgi.jar` or that I needed to run `spreadsheet.flushOsgiBundle();`. I did both at once and it now works. The code I had was pretty much exactly how my code was configured for testing this. I appreciate the prompt response! 

BTW, `dump( server.java.version );` reported `"16"` (vendor: Oracle, archModel: 64)
