### ISSUE TITLE
addRows - specify spreadsheet

### ISSUE THREAD

**Issue by Daemach** [cfsimplicity/lucee-spreadsheet#241]
How do I specify in which spreadsheet within a workbook to add rows?

**Comment by cfsimplicity** [comment]
Just use [setActiveSheet()](https://github.com/cfsimplicity/lucee-spreadsheet/wiki/setActiveSheet) or [setActiveSheetNumber()](https://github.com/cfsimplicity/lucee-spreadsheet/wiki/setActiveSheetNumber) before adding the rows.
