### ISSUE TITLE
 	luceeSpreadsheet/HeaderImageVML has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by Daemach** [cfsimplicity/lucee-spreadsheet#242]
I just installed the latest version of Java 8 - not sure where to get java 11 for windows...  If that's what's required, can you point me in the right direction?

**Comment by cfsimplicity** [comment]
I use [AdoptOpenJDK ](https://adoptopenjdk.net/) which has Windows versions.

But the library is supposed to support Java 1.8 so this my fault for not compiling the HeaderImageVML java source with that in mind.

I've altered the build to fix that. Can you try with the latest develop branch and check it works? Please re-open the ticket if not.
