### ISSUE TITLE
getXSSFColor returns null

### ISSUE THREAD

**Issue by GaryStanton** [cfsimplicity/lucee-spreadsheet#243]
I'm not sure how to reproduce this, but I have a spreadsheet I'm reading in and adding data to.
When attempting to do any formatting to the cells, I'm getting an error due to `getXSSFColor` returning null in the `setColor` call of the `cloneFont` function (around line 2994).

A workaround for me is simply to check that a colour is returned first and use a default if not. Happy to put this into a pull request if you're ok with it - I'm afraid I've no idea what causes the issue in the first place.

```
var color = isXmlFormat( arguments.workbook )? arguments.fontToClone.getXSSFColor(): arguments.fontToClone.getColor();
newFont.setColor( isDefined('color') ? color : fontToClone.DEFAULT_FONT_COLOR );
```

**Comment by cfsimplicity** [comment]
Shame we can't identify the cause, Gary, but I've implemented a similar fix. Can you check it with the latest develop branch?

**Comment by GaryStanton** [comment]
Thanks yes, that seems to work for me... though the dev version seems significantly different to the version I'm running so I must be on an old version!

**Comment by cfsimplicity** [comment]
Yes, I assumed you were on quite an old version from the line number you gave. The version property should be right at the top of Spreadsheet.cfc

I'll knock out a new release which includes this fix in the next few days all being well.
