### ISSUE TITLE
Auto-column width

### ISSUE THREAD

**Issue by Daemach** [cfsimplicity/lucee-spreadsheet#244]
I don't know if it's possible with built-in library functionality, but I would love to see an auto-columnwidth formatting feature.  autoColumnWidth: true would be so useful....

**Comment by Daemach** [comment]
or setColumnWidth('auto')

**Comment by Daemach** [comment]
spreadsheet.setColumnWidth( workbook, 1-12, 'auto' );

**Comment by cfsimplicity** [comment]
You already have [autoSizeColumn()](https://github.com/cfsimplicity/lucee-spreadsheet/wiki/autoSizeColumn), plus you can specify `autosize` with [addColumn()](https://github.com/cfsimplicity/lucee-spreadsheet/wiki/addColumn), and `autosizeColumns` with [addRow()](https://github.com/cfsimplicity/lucee-spreadsheet/wiki/addRow) and [addRows()](https://github.com/cfsimplicity/lucee-spreadsheet/wiki/addRows).

**Comment by Daemach** [comment]
How did I miss all of those...?

Thanks!

**Comment by Daemach** [comment]
It would be great if this setting could be added to workbookFromQuery as well.
