### ISSUE TITLE
Formats not sticking

### ISSUE THREAD

**Issue by Daemach** [cfsimplicity/lucee-spreadsheet#249]
I'm sure I'm doing something wrong here, but I can't figure out what that is...  I am trying to format a number of rows with a grey background to make them stand out (btw, why fgcolor instead of bgcolor?  text is in the foreground...)  Oddly, the second formatRow() call is working - first row is centered and bold, but none of the "receiptRows" is highlighted.  Can you point me in the right direction?  RecieptRows is an array full of numbers, btw...

```
    var workbook = spreadsheet.workbookFromQuery( data, true , true , true , true, 100, true, {
      date: ['Trade Date','Next Dividend Date','Next Ex-Dividend Date','Entry Date','Settlement Date','OriginalCostDate']
    })
    //spreadsheet.addFreezePane( workbook, 11, 1)
    //dump(receiptRows);abort;

    commonFormat = { fgcolor: '230,230,230' }; 
    highlight = spreadsheet.createCellStyle( workbook, commonFormat );

    receiptRows.each((row)=>{
      systemoutput('formatting row #row#')
      spreadsheet.formatRow( workbook=workbook, row=row, cellStyle=highlight );
    })
    
    spreadsheet.formatRow( workbook, { alignment: 'center', bold: true }, 1)
```

**Comment by Daemach** [comment]
GREY_25_PERCENT doesn't work either...+

**Comment by cfsimplicity** [comment]
Try using the normal XSSF format rather than SXSSF (streaming xml).

SXSSF is designed to be more memory efficient but there's a trade-off in that once the rows outside the memory window have been written to disk [they can't be changed](https://github.com/cfsimplicity/lucee-spreadsheet/wiki/newStreamingXlsx).

See also this [related issue](https://github.com/cfsimplicity/lucee-spreadsheet/issues/230#issuecomment-800587563).

**Comment by cfsimplicity** [comment]
> btw, why fgcolor instead of bgcolor? text is in the foreground...

Good question. I inherited that rom the old cfspreadsheet extension, which took it from ACF's implementation.

In POI terms, text colour is set using the `font` object, and there are separate methods for setting the foreground and background cell fill colours, but I'm not sure how these last two differ in effect. There is also a cell fill pattern property which I think may complicate things.

But I agree the naming isn't ideal so I'll take a look at it when I get chance.

**Comment by Daemach** [comment]
Makes sense.  Thanks for your work on this!

And switching formats solved the problem!

**Comment by Daemach** [comment]
So the reason I switched to streaming is that I am processing a 180mb spreadsheet from a financial services dump.  Import spreadsheet, convert to query, process line by line, create new output workbook, add 2 tabs with compiled info, format for readability then save.  Except it crashes before it finishes.  Can you recommend a workflow that might help?  I'm on my 4th run of the day after increasing the java heap size to 16GB - may work this time but if not, it would be great to know what to try next.  I would hate to have to save as csv and read line by line because of the string qualifiers.

**Comment by cfsimplicity** [comment]
I think increasing heap memory is probably your only option. SXSSF will solve the "write" part of the workflow, but at the expense of the formatting. And then you'd still have a problem with the initial read.

Sorry I can't offer a solution. I wish there were better built-in support for large files in POI as it's quite a common use case.
