### ISSUE TITLE
Multi-cell formatting methods throw invalid arguments exception if overwriteCurrentStyle is set to false

### ISSUE THREAD

**Issue by Daemach** [cfsimplicity/lucee-spreadsheet#250]
I'm not sure what I'm doing wrong here:

![image](https://user-images.githubusercontent.com/12553953/122275625-c3c8ce00-ce98-11eb-91ef-3d8d18a2461c.png)

**Comment by Daemach** [comment]
Hmm - I did apply a cell style previously.  That's likely what it means.  Error message might be changed to something like 'overwriteCellStyle' cannot be false if a cellStyle was applied.

**Comment by cfsimplicity** [comment]
No, there is an issue with the error logic. Your `formatCellRange()` call is perfectly valid. Will fix.

**Comment by cfsimplicity** [comment]
Actually it seems there's a more substantial issue with the `overwriteCurrentStyle` argument not being respected when `false` with the multi-cell formatting methods. To be honest it's best left as `true` to avoid performance problems, but it should work if you make that choice.

Again, will sort it out when I can.

**Comment by Daemach** [comment]
I read that.  I only need it in a couple of cells, so I'm not worried about
performance.

Thanks Julian!

**Comment by cfsimplicity** [comment]
I've put in a fix. Would you be able to test it with the develop branch? Thanks.

**Comment by Daemach** [comment]
I installed from forgebox.  How would I do that?

**Comment by cfsimplicity** [comment]
Probably best to install it manually. I would download the zip using the green Code button on the main Github page, extract to a temp location, then temporarily point your calling code to it when instantiating the library.

But if it's a pain, don't worry. I have written tests, it's just good to get confirmation for fixes.

**Comment by Daemach** [comment]
I will try to give that a shot later today. I’m deep in the middle of a
project though.

Thanks for your timely response as always!

**Comment by cfsimplicity** [comment]
I've released the fix version, John, so you can update from Forgebox.
