### ISSUE TITLE
Feature Request: SafeColumnNames

### ISSUE THREAD

**Issue by JamoCA** [cfsimplicity/lucee-spreadsheet#251]
Back in 2004, I used a cfx_Excel2Query java tag (by Ryan D. Emerle) that had apache POI bundled and performed simple transformations of XLS file to query objects.  In version 1.0.2, he added a feature to sanitize & unique-ify column names. The changelog indicated the following notes:

> - Fixed problem with special characters in user-specified columns
> Now columns with period or slashes (forward or back) will 
> have those characters replaced with underscores.  Output
> #query_name.columnlist# to see your column names. 
> [Thanks to Micah LaCombe]

Using lucee spreadsheet, I can import almost any Excel, CSV or TSV file, but that doesn't mean that the resultant query object is useable. While Lucee enables the use of bracket notation to rename invalid column names through the use of query-of-queries (QofQ), there's a [bug](https://tracker.adobe.com/#/view/CF-4212034) in Adobe ColdFusion preventing it from working.  I don't believe there's any post-query cfml-only solution for handling duplicate column names.  You can attempt to use the undocumented `SetColumnNames()` method, but that appears to be cosmetic as ACF continues to use the initial column names when trying to perform QofQ operations.

Here's some test data.

```
id	id	A B C	x/y	a:b	(a)	a"b'c	<a>	a-b=c
1	1	1	1	1	1	1	1	1
2	2	2	2	2	2	2	2	2
3	3	3	3	3	3	3	3	3
```

While this is successfully turned into a query object and faithfully retains the same column names, one duplicate `id` column is unable to be referenced and you can't perform any QoQ operations that reference any of the invalidly named columns.

I believe that the cfx_Excel2Query tag would have automatically (by default) sanitized & deduped the incoming column names to something like this:
```
id	id2	A_B_C	x_y	a_b	a	a_b_c2	a2	a_b_c3
```

Adding this feature would be very beneficial and prevent me from requesting that clients learn to rename their columns to something CFML-compatible.

**Comment by cfsimplicity** [comment]
I blogged about [renaming query columns](https://blog.simplicityweb.co.uk/125/renaming-cfml-query-columns) recently, with a rather clunky workaround for ACF which I use in the library.

But as you say that wouldn't address the problem duplicate names. Lucee actually throws an error if you try to read a spreadsheet with duplicate header row values, as it's using `QueryNew()` directly.

I agree it would be good to be able to handle this. Let me have a ponder on how best to do it.

**Comment by JamoCA** [comment]
I just wrote this for my use.  Thoughts?

```
array function sanitizeColumnNames(query query) {
	local.nameCount = {};
	if (structKeyExists(server, "lucee")){
		local.columnNames = arguments.query.getColumnNames();
	} else {
		local.columnNames = arguments.query.getMetaData().getColumnLabels();
	}
	for(local.i=1; local.i lte arrayLen(local.columnNames); local.i+=1){
		local.newName = javacast("string", local.columnNames[local.i]).trim().replaceAll("##","Num").replaceAll("[^A-Za-z0-9_]", "_").replaceAll("_{2,}", "_");
		if (local.nameCount.keyExists(local.newName)){
			local.nameCount[local.newName] += 1;
			local.newName = local.newName & local.nameCount[local.newName];
		} else {
			local.nameCount[local.newName] = 1;
		}
		local.columnNames[local.i] = local.newName;
	}
	return local.columnNames;
}
```

**Comment by JamoCA** [comment]
BTW, the "queryRenameColumns" UDF isn't compatible with CF2016.  I had to rewrite `len()` and `findNoCase()` member functions as that syntax isn't supported by CF2016.

While it works where other methods fail, I know some things will be lost in conversion due to JSON serialization limitations.  I would advise caution and only use it when working with simple data from CSV, TSV or XLS/XLSX files and if column types are simple, ie VARCHAR & INT. (I work with some "time" data types that require precision as well as the GEOGRAPHY data types.)

**Comment by cfsimplicity** [comment]
The UDF works fine for me with ACF 2016,0,17,325979 running in CommandBox.

I also use `.Len()` and `.FindNoCase()` quite a lot in the library which works fine with ACF2016.

As I say the serialization method is a bit clunky, but currently it's the best solution I have for ACF where the spreadsheet header values are invalid variable names.

Thanks for the code suggestion. I'll take a closer look when I get chance.

**Comment by cfsimplicity** [comment]
I've added a new `makeColumnNamesSafe` option (defaulting to `false`) to `read()` and `csvToQuery()` on the develop branch. Can you give it a try?

**Comment by JamoCA** [comment]
I tested `csvToQuery`.  I'm not a fan of query column names containing leading or trailing underscores, but it seemed to work without error when reusing as an ACF2016 query-of-queries.
