### ISSUE TITLE
Allow WriteToCSV to exclude the workbook's header row

### ISSUE THREAD

**Issue by Daemach** [cfsimplicity/lucee-spreadsheet#252]
The docs page for writetocsv shows write( workbook, filepath [, overwrite [, delimiter ] ] ) as the function call.  

Also, would it be possible/easy to add a parameter that defaults true for include header row?  Sounds odd, but I have to generate files that cannot include a header row and takes time to remove them.  Not a huge deal if not, but would keep my code cleaner if possible.

**Comment by cfsimplicity** [comment]
Thanks for spotting the docs error, John. Fixed.

Happy to add `includeHeaderRow` as an option to `writeToCsv()`.
