### ISSUE TITLE
Reading empty spreadsheet throws an error.

### ISSUE THREAD

**Issue by JamoCA** [cfsimplicity/lucee-spreadsheet#263]
A client accidently uploaded an empty XLS file and stated that they got a ColdFusion error.

```
Variable HEADERROWOBJECT is undefined.
The error occurred in .../helpers/sheet.cfc: line 162

161: var headerRowObject = sheet.object.getRow( JavaCast( "int", sheet.headerRowIndex ) );
162: var rowData = getRowHelper().getRowData( arguments.workbook, headerRowObject, sheet.columnRanges );
```

I'm guessing it's because `getRow()` returns `NULL` and `getRowData()` doesn't accept it.  I'd expect that it would return an empty query (ie, `queryNew("")`).

**Comment by cfsimplicity** [comment]
With minimal arguments it would have returned an empty query, but with`headerRow` specified the library was trying to get that non-existent row to generate the query column names.

Definitely shouldn't do that. Fix coming up...
