### ISSUE TITLE
queryToCsv with empty query returns incorrectly delimited header row

### ISSUE THREAD

**Issue by JamoCA** [cfsimplicity/lucee-spreadsheet#292]
Using v3.4.4, I used [queryToCsv](https://github.com/cfsimplicity/spreadsheet-cfml/wiki/queryToCsv) to backup sets of data, but in some cases "no results" are returned.

When exporting using the following settings (using `tab` as a delimiter):
```
spreadsheet.queryToCsv(query=myQuery, includeHeaderRow=true, delimiter=chr(9));
```

The header incorrectly used a period as a delimiter:
```
COL1.COL2.COL3
```
... instead of tabs:
```
COL1	COL2	COL3
```

**Comment by JamoCA** [comment]
Hmm... I see that.

Perhaps it's an issue with FileWrite.  Try this with the tab-delimited CSV results.  (NOTE: I'm using ACF2016.)
```
filewrite("c:\emptyquery.csv", result, "utf-8");
```

This converts the tabs to periods. I don't think I've ever seen this before.  (I'll test later in ACF2021 and latest Lucee.)

**Comment by cfsimplicity** [comment]
Getting the same (expected) result in the file using Lucee.

**Comment by cfsimplicity** [comment]
Getting the same result in the file with each of ACF2016, 2018 and 2021:
```
myQuery = QueryNew( "column1,column2", "VarChar,VarChar", [] );
result = spreadsheet.queryToCsv( query=myQuery, includeHeaderRow=true, delimiter=chr(9) );
WriteDump( result );
Filewrite( ExpandPath( "emptyquery.csv" ), result, "utf-8");
```
