### ISSUE TITLE
Add support for addInfo() and info()

### ISSUE THREAD

**Issue by cfsimplicity** [cfsimplicity/lucee-spreadsheet#30]

**Comment by JamoCA** [comment]
I'm not sure if v2.7.0 is working in Adobe ColdFusion 2016.  When I attempt to use `addInfo` using the [sample code](https://github.com/cfsimplicity/lucee-spreadsheet/wiki/addInfo), it throws an error:



| The getProperties method was not found. |
| --- |
| <font style="box-sizing: inherit; color: black; font: 8pt / 11pt verdana;">Either there are no methods with the specified method name and argument types or the getProperties method is overloaded with argument types that ColdFusion cannot decipher reliably. ColdFusion found 0 methods that match the provided arguments. If this is a Java object and you verified that the method exists, use the javacast function to reduce ambiguity.</font> |
|   |
| <font style="box-sizing: inherit; color: black; font: 8pt / 11pt verdana;">The error occurred in<span> </span><b style="box-sizing: inherit;">C:/CFusion/cfusion/CustomTags/luceeSpreadsheet/Spreadsheet.cfc: line 1693</b><br style="box-sizing: inherit;"><b style="box-sizing: inherit;">Called from</b><span> </span>C:/CFusion/cfusion/CustomTags/luceeSpreadsheet/Spreadsheet.cfc: line 461<br style="box-sizing: inherit;"><b style="box-sizing: inherit;">Called from</b><span> </span>D:/www/test/luceeSpreadsheet_test.cfm: line 209<br style="box-sizing: inherit;"><b style="box-sizing: inherit;">Called from</b><span> </span>D:/www/test/luceeSpreadsheet_test.cfm: line 1<br style="box-sizing: inherit;"><b style="box-sizing: inherit;">Called from</b><span> </span>D:/www/test/index.cfm: line 254<br style="box-sizing: inherit;"><b style="box-sizing: inherit;">Called from</b><span> </span>D:/www/test/Application.cfc: line 71<br style="box-sizing: inherit;"></font> |
| <br>```<br>1691 : 
1692 : 	private void function addInfoXml( required workbook, required struct info ){
1693 : 		var documentProperties = arguments.workbook.getProperties().getExtendedProperties().getUnderlyingProperties();
1694 : 		var coreProperties = arguments.workbook.getProperties().getCoreProperties();
1695 : 		for( var key in arguments.info ){<br>```<br> |
