### ISSUE TITLE
Support demerge of cells

### ISSUE THREAD

**Issue by tomchiverton** [cfsimplicity/lucee-spreadsheet#47]
If the input Excel file contains merged cells, then some cells in the query will be blank, but should be filled in.
Cells can be unmerged using the underlying POI classes, as long as the query contains blank rows and columns, or the numbering is off.
```
q = spreadsheet.read( src=filepath,format="query", sheetName=sheetName,includeBlankRows=true);//req blank rows to undo cell merge
o = spreadsheet.read( src=filepath );//a org.apache.poi.hssf.usermodel.HSSFWorkbook
o = o.getSheet(sheetName);
for(r=0;r lt o.getNumMergedRegions();r++){
	reg=o.getMergedRegion(r);//a org.apache.poi.ss.util.CellRangeAddress
	roww=o.getRow( reg.getFirstRow() );
	cell=roww.getCell( reg.getFirstColumn() );
	str=cell.getRichStringCellValue().getString();
	for(row=reg.getFirstRow();row lte reg.getLastRow();row++){
		for(col=reg.getFirstColumn();col lte reg.getLastColumn();col++){
			q['column'&col+1][row+1]=str;
		}
	}
}
```
It would be nice to have this as an option to read(format="query"), but without having to include blank rows/cols, which probably means moving the blank removal to after the read, hence not attaching a trivial patch here !
I suppose you could throw an error if format="query",includeblanklines!=true,unmerge=true instead ?

**Comment by cfsimplicity** [comment]
Hi Tom. My understanding of cell merging is that it's primarily a visual effect. The underlying data grid remains and the data may or may not, depending on how you performed the merge. The `mergeCells()` function in this library keeps the data but just visually hides all but the top-left-most value.

I think by default Excel will delete the data not shown when merging, leaving empty cells in the underlying grid. I use OpenOffice which gives you a choice of what to do with the merged cell data.

If merging does leave actual blanks then you say they "should be filled in" when converting to a query. But why and with what?

I ran your code on a sheet where A1:B2 had been merged and the values in A2, B1 and B2 physically deleted (not just hidden). The resulting query had the A1 value repeated in all 4 merged cells. Is that what you intended? If so, why would you want to do that?

Sorry if I'm missing your point.

**Comment by tomchiverton** [comment]
Well, here's the case that lead to me needing to do it.
We're importing a spreadsheet with items in columns, and their properties in the rows. The source .xls "helpfully" has common properties merged across columns.
So when the query is returned, we get

```
empty,Type One, Type Two
prop A,value 1, value 2
prop B,value 3,[empty]
```
the intent of the demerge code would be to get
```
empty,Type One, Type Two
prop A,value 1, value 2
prop B,value 3, value 3
```

**Comment by cfsimplicity** [comment]
Yes, I've been thinking about this and can now see how it might be useful.

I don't think "de-merge" is the right term though. That suggests cells will be restored to their state prior to the merge. The values might be the same, as in your case, but there's no way of knowing for sure what the original values were before they were blanked by the merge AFAIK.

I'm thinking an attribute such as `fillMergedCellsWithVisibleValue` would be more descriptive, if a bit long-winded.

**Comment by cfsimplicity** [comment]
Tom, I've added an option to `read()` which I hope will meet your need. It won't clash with `includeEmptyRows' because the "de-merge" (as you call it) takes place on the sheet object *before* it is converted to a query. Any problems, let me know.
