### ISSUE TITLE
Does not export formatted text

### ISSUE THREAD

**Issue by tomchiverton** [cfsimplicity/lucee-spreadsheet#57]
I have a cell with the visible value having a partial strike through
£99 ~~£55~~
There's no way to extract the formatted text, instead the value is retrieved as 
£99 £55

**Comment by tomchiverton** [comment]
In outline it seems like a change in tools.getRowData() would work.

If cellType is STRING and cell.getRichStringCellValue().numFormattingRuns() isn't 0, then build a HTML formatted string from the results of workbook.getFontAt(rich.getFontOfFormattingRun(n)) and the helps in HSSFRichTextString.

Hide the extra work behind a boolean in the call to read() so people who don't care about the format of the cell can get back just the raw text.

Someone must already have written such a parser...

**Comment by cfsimplicity** [comment]
Formatting is really just a visual layer on top of the data values, so to my mind it's mostly only appropriate when outputting to a spreadsheet object that will be viewed in Excel or something else that can display it.

If you're going the other way and reading into a query, then I think it's reasonable to expect you'll just get the raw values without formatting.

I take your point with your strikethrough example, but strictly speaking that data should be structured without relying on formatting if it needs to be portable. An option to somehow parse and mark-up formatted values might be useful in cases like this, but frankly it does sound quite tricky.

**Comment by tomchiverton** [comment]
Yes, it's for input from Excel, and the raw text is a good default. People are editing the spread sheet, and we can't relie on them to always enter structured data, because people :-)

I have a mockup mostly working locally, I think. Just need to get my head around HSSFColor and then it'll return cell values as "£99 <span class="text-decoration:line-through" >£55</span>" (or what ever CSS styles are need to represent the formatting).
It's not that bad, Most of the work is finding the formatted ranges.

For my ultimate aim this is OK, and I'll hide it behind a new option to read(). 
I assume you'd still be happy to merge the feature ?

**Comment by cfsimplicity** [comment]
I'd need to see how it worked I think. I'm still a bit doubtful about the idea of "styles" post-read. It's making an assumption that what you read the data into will understand the CSS. Databases obviously won't. If you're reading into HTML or expecting the database to output to a browser later, then it makes more sense of course.

Maybe ok as an option, but too many options can lead to bloated, overly-complex software. Happy to consider it though. I can certainly see the use case.

**Comment by tomchiverton** [comment]
See #60
