### ISSUE TITLE
Please add setRepeatingRowsAndColumns or setRepeatingColumns support

### ISSUE THREAD

**Issue by jyuskus** [cfsimplicity/lucee-spreadsheet#66]
Can you add the older setRepeatingRowsAndColumns or the newer setRepeatingColumns?

**Comment by cfsimplicity** [comment]
Thanks for the suggestion. Have added to the master branch. Can you confirm it does what you want? If so I'll release as 0.5.5. Docs in the wiki.

**Comment by jyuskus** [comment]
Works great.

Thank you.

**Comment by lmah** [comment]
Hi, I am wondering if you are able to create a password protected spreadsheet? I notice you still have a comment (TODO: workbook.isWriteProtected() returns true but the workbook opens without prompting for a password).

**Comment by cfsimplicity** [comment]
Hi. The TODO was inherited from the old Railo Extension on which this library's based. I've created a new ticket and will look into it:

https://github.com/cfsimplicity/lucee-spreadsheet/issues/68
