### ISSUE TITLE
Writing a file with password protection doesn't work

### ISSUE THREAD

**Issue by cfsimplicity** [cfsimplicity/lucee-spreadsheet#68]
Inherited from Railo Extension. Supplying a password only makes the file "read-only". Doesn't prevent opening.

**Comment by cfsimplicity** [comment]
POI's support for password protection seems to be patchy. You can prevent XML spreadsheet files (.xlsx) from being opened without a password, but not binary (.xls) workbooks.

Conversely you can prevent a binary workbook from being edited, but this doesn't work for XML workbooks.

I've decided to make the `password` attribute of `write()` trigger the XML-only file encryption. If the workbook is binary instead of XML it will throw an exception.

I've also created a separate `setReadOnly()` function which works with binary workbooks: https://github.com/cfsimplicity/lucee-spreadsheet/issues/69

@Imah could you please download the current Master and see if the password protection in `write()` works for you now. As I say it will only work with XML format spreadsheets. Also note that not all spreadsheet software supports the type of encryption used. I was able to open protected files with Excel Viewer but not OpenOffice.

**Comment by lmah** [comment]
Hi Julian,

I followed your example you had, for write() to test out XML spreadsheet creation,
spreadsheet = service("spreadsheet");
data = QueryNew( "First,Last","VarChar,VarChar",[ [ "Susi","Sorglos" ],[ "Julian","Halliwell" ] ] );
workbook = spreadsheet.workbookFromQuery( data );
path = "C:/temp/test.xlsx";
spreadsheet.write( workbook=workbook, filepath=path, password="testpassword");

But, that still throws an error (not sure if I was doing something wrong there?): 
Message	Whole file password protection is not supported for binary workbooks
Detail	Password protection only works with XML ('xlsx') workbooks.

I did come across some post regarding password proctection, I.e. 
http://sachinnikam.blogspot.com.au/2014/04/apache-poi-password-protected-excel.html

using Biff8EncryptionKey,

however, with my limited Java skills, not sure if this would work for binary (xls) workbook?


Regards,
Leroy

**Comment by cfsimplicity** [comment]
Hi Leroy, the example code you used creates a *binary* file. You need to add the `xmlFormat` flag to `workbookFromQuery` to generate an XML file:
```
spreadsheet = service("spreadsheet");
data = QueryNew( "First,Last","VarChar,VarChar",[ [ "Susi","Sorglos" ],[ "Julian","Halliwell" ] ] );
workbook = spreadsheet.workbookFromQuery( data=data,xmlFormat=true );
path = "C:/temp/test.xlsx";
spreadsheet.write( workbook=workbook, filepath=path, password="testpassword");
```
The POI docs suggest (but aren't very clear) that `Biff8EncryptionKey` could be used for writing password protected binary files, but the example they give is for reading only. 

I tried adapting it for writing but couldn't get it to work. I'm not a Java developer either so it may be I was doing it wrong. I'll take a look at the blog you mention and see if that works any better.

Thanks.
Julian.

**Comment by cfsimplicity** [comment]
Leroy, I've looked at the blog post and it's actually just creating a "read-only" file. It can still be opened without the password as the author does mention. I have already added a `setReadOnly()` method which uses the `writeProtectWorkbook()` POI method used in the post.

As I say the POI docs do suggest `Biff8EncryptionKey` can be used when saving binary files, but I've tried and can't get it to prevent the file from being opened.

**Comment by lmah** [comment]
Hi Julian,

Thanks very much for looking into this. I can confirm that the XML spreadsheet can be created with password pro
You can prevent XML spreadsheet files (.xlsx) from being opened without a password, but not binary (.xls) workbooks.

**Comment by lmah** [comment]
Julian, are you able to open a password protected XML spreadsheet?

**Comment by cfsimplicity** [comment]
Hi Leroy, as I mentioned earlier I've found that the encrypted XLSX files can be opened (with the correct password) by MS Excel Viewer (I don't have the full MS Excel, but assume it will work with that too), but not by OpenOffice.

**Comment by lmah** [comment]
Hi Julian, 

Sorry I meant using the read function from your code. Is it able to open and read a password protected excel file, parsing the password as an argument ? 

Regards 
Leroy

**Comment by cfsimplicity** [comment]
No the `read()` method doesn't support specifiying a password. Please open a ticket if that's something you need and I'll experiment with it. But given how patchy the POI encryption support is I'm not sure how effective it'll be.

**Comment by lmah** [comment]
Hi Julian,

Hope you had a great Christmas. I have created a ticket in GitHub regarding
this, and am wondering if this is something you will be looking into in
near future? I need to get this project launch (which involves creating and
reading password protected Excel spreadsheet) in mid January 2016, and am
wondering if this time frame is feasible?


Thanks,
Leroy

**Comment by cfsimplicity** [comment]
Hi Leroy. See my comment on your ticket: https://github.com/cfsimplicity/lucee-spreadsheet/issues/70
