### ISSUE TITLE
Read() password protected spreadsheet 

### ISSUE THREAD

**Issue by lmah** [cfsimplicity/lucee-spreadsheet#70]
Can the read()  function read a password protected spreadsheet with a password passed as argument? 

Thanks

**Comment by cfsimplicity** [comment]
Leroy, I've added some tests to the automated suite for reading and writing encrypted files, but could you please download the master branch and check it all works in your own environment? Again I must stress that only XML (.xlsx) files are supported.

**Comment by lmah** [comment]
This works perfectly as described! Thanks Julian!
