### ISSUE TITLE
Installed and casting issues with test suite.

### ISSUE THREAD

**Issue by mchupp** [cfsimplicity/lucee-spreadsheet#71]
I have installed  files and testbox, performed the mappings successfully.  The test suite runs but returns quite a few errors, most have to do with casting issues.

Here is the error for addColumn:

+spreadsheet test suite (1170 ms)
+addColumn tests (24 ms)
Adds a column with the minimum arguments (3 ms) - invalid call of the function addColumn (C:\xxx\lucee-spreadsheet-master\Spreadsheet.cfc), second Argument (data) is of invalid type, can't cast Object type [Struct] to a value of type [string] +
Adds a column at a given start row (2 ms) - invalid call of the function addColumn (C:\xxx\lucee-spreadsheet-master\Spreadsheet.cfc), second Argument (data) is of invalid type, can't cast Object type [Struct] to a value of type [string] +
Adds a column at a given column number (2 ms) - invalid call of the function addColumn (C:\xxx\lucee-spreadsheet-master\Spreadsheet.cfc), second Argument (data) is of invalid type, can't cast Object type [Struct] to a value of type [string] +
Adds a column including commas with a custom delimiter (5 ms)
Inserts (not replaces) a column with the minimum arguments (2 ms) - invalid call of the function addColumn (C:\xxx\lucee-spreadsheet-master\Spreadsheet.cfc), second Argument (data) is of invalid type, can't cast Object type [Struct] to a value of type [string] +
Adds numeric, boolean or date values correctly (9 ms)

**Comment by cfsimplicity** [comment]
The tests all pass in my environment. The value of the `data` argument in the tests that are failing in yours is "a,b", i.e. a comma delimited list: definitely a string, not a struct. I can't think what could be happening in your environment that is causing it to be treated as a struct.

What version of Lucee are you using? Do you have any non-standard settings in the Admin?

**Comment by cfsimplicity** [comment]
Maybe the `variables.data` value in the beforeEach() function is somehow being overridden in your environment. Try dumping it in the first addColumn test to see what's in that variable at runtime.

```
it( "Adds a column with the minimum arguments",function() {
		dump( data );
		s.addColumn( workbook,data );
...
```

**Comment by cfsimplicity** [comment]
OK, I've found the cause: you must be using TestBox version 2.2. The tests were written against version 2.1 (I do specify that version in the ReadMe). Something's obviously changed in TestBox to cause this. I've opened a ticket to upgrade support for 2.2.

**Comment by cfsimplicity** [comment]
This seems to be a bug in TestBox 2.2 which prevents the variable name `data` being used without being scoped. I've raised a ticket on TB's bug tracker: https://ortussolutions.atlassian.net/browse/TESTBOX-159
