### ISSUE TITLE
Extend row limit beyond 65535

### ISSUE THREAD

**Issue by jyuskus** [cfsimplicity/lucee-spreadsheet#74]
Current limit of rows is 65535, can you extend this beyond the limit for for a 16 bit integer?

Error received:
Invalid row number (65536) outside allowable range (0..65535) 
The error occurred on line 149 in file tools.cfm.

**Comment by cfsimplicity** [comment]
That 65535 limit is imposed by POI for the binary spreadsheet format, so there's nothing I can do about that. However, the XML format (.xlsx) supports up to a million apparently. The library allows you to specify the format when creating spreadsheets.

https://poi.apache.org/apidocs/org/apache/poi/ss/SpreadsheetVersion.html
