### ISSUE TITLE
Invalid color after moving from Lucee 4.5.3 to Lucee 5.0

### ISSUE THREAD

**Issue by cfprogrammer** [cfsimplicity/lucee-spreadsheet#87]
Hi Julian,
I am getting the error below On a box that has Lucee 5.0  The exact same code is working on a box with Lucee 4.5.3.  Do you have any idea what might  cause this.

I have tried :
`format={bottomborder='thick',topborder='medium',fgcolor='yellow',bold=true}`
`format={bottomborder='thick',topborder='medium',##fgcolor='yellow',bold=true}`
Both produce the invalid color error
`format={bottomborder='thick',topborder='medium',#fgcolor='yellow',bold=true}`
Obviously doesn't work because the the single "#" but I thought I'd try

Is there some other format that could work?

The only other thing I notice in the set up is that the older box's (lucee 4.5.3) java version is 1.7 32bit and the new box's (lucee 5.0) java version is 1.8 64bit

![image](https://cloud.githubusercontent.com/assets/12588948/17112328/79e56c22-525a-11e6-9ac5-444c18f6ff11.png)

**Comment by cfsimplicity** [comment]
Hi, I'm running Lucee 4.5.3 with Java 1.8 64 bit and I'm not seeing that error, so I think we can discount the Java version.

I don't have Lucee 5, but I'll set it up with the some tests to see if I can replicate the problem and get back to you.

**Comment by cfsimplicity** [comment]
It wasn't the color name or syntax that was causing the problem, but the way the java class that handles color was being called. This worked in Lucee 4.5 because an old version of POI ships with it, whereas version 5 doesn't include POI at all.

Latest version should work in 5 now.

**Comment by cfsimplicity** [comment]
Oh, and thanks very much for reporting it - defnitely a bug that needed sorting!

**Comment by cfprogrammer** [comment]
Confirmed this is working correctly on Lucee 5.0 Thanks as always for such a quick response and fix
