### ISSUE TITLE
Update JavaLoader to work with strict scoping

### ISSUE THREAD

**Issue by PrevenPillay** [cfsimplicity/lucee-spreadsheet#94]
Hi,

I've not done much in Github, so forgive me if I don't follow some guidelines.

I'm running a Lucee installation where when I set Settings > Scope >Cascading to “Strict”, I get an error when trying to use your spreadsheet library, because of the javaLoader.cfc lines 441 and 445, where the `name` variable will throw an [name] is undefined error. I fixed it by changing them to `qJars.name`.

I know it's technically an issue with JavaLoader but I don't know where it's repo is and I figured since you package it with the spreadsheet library, it might be worth updating it here.

Thanks!

**Comment by cfsimplicity** [comment]
Hi, [here's the repo for JavaLoader](https://github.com/markmandel/JavaLoader), but as you can see it's no longer being updated.

But I also use strict scope cascading in all my apps and I haven't come across this issue nor has anyone else reported it. I've run the test suite with `this.scopeCascading = "strict";` and also with that setting turned on in the Lucee admin and there are no errors.

Does the error occur when you try to use any method in the library? Could there be something specific to your environment that's causing this?

I'm not really keen on customising the bundled JavaLoader as the idea now is that it's an optional dependency. To avoid duplication you can specify the path to an existing JavaLoader installation which may or may not have your suggested patch.

**Comment by PrevenPillay** [comment]
Argh my mistake, I forgot to state that it happens when running the `.new()` method, just creating a new instance of the library works fine.

I do agree though, I should rather try to get it changed in JavaLoader instead(and thanks for the link, I might as well try to get a pull request for that repo). I ended up creating a modified JavaLoader installation and pointed the library to use it.

**Comment by cfsimplicity** [comment]
No worries, I think it's a valid issue, but I'm still puzzled as the test suite covers the `new()` method and is not picking up any errors even with that setting. What version of Lucee are you using?

Actually it seems [a patch was applied](https://github.com/markmandel/JavaLoader/pull/5) to the master branch of JavaLoader to fix this for Railo a short while after the final 1.1 release in 2012.

I'd be happy to update the bundled JL with that later master version. I'll test it shortly and update the master branch here. If you could then check it for me that would be great.

**Comment by cfsimplicity** [comment]
Sorry, I meant the "develop" version of JavaLoader, not master. That's where the patches are.

**Comment by PrevenPillay** [comment]
Sure, I'd be happy to test out any changes. My version of Lucee is `Lucee 4.5.2.018 final`.
And thanks for finding that change in the develop branch, gives me some assurance that I wasn't going crazy.

**Comment by cfsimplicity** [comment]
OK, I'm on 4.5.3.020 but doubt that's an issue. I was on your older version for quite a while and still never saw the problem.

I've pushed the updated JavaLoader to the current master branch. Could you test and let me know the result?

**Comment by PrevenPillay** [comment]
Thanks alot for your help. I gave it a shot and it works perfectly!

**Comment by cfsimplicity** [comment]
Great, thanks for confirming.
